const SYSTEM = '你是企业内部内容增长工作流中的专业内容分析 Agent。只分析公开信息，不虚构事实，不照抄原文，不输出平台未提供的数据。必须严格输出 JSON。';

function candidateTextAnalysisPrompt(candidate) {
  return `这是候选图文的第一阶段文本分析。只分析标题、正文、话题和公开互动数据，不要猜测图片内容。\n\n平台：${candidate.platform}\n标题：${candidate.title}\n作者：${candidate.author}\n关键词：${candidate.keyword || ''}\n发布时间：${candidate.publishedAt || candidate.publishedAtRaw || '未知'}\n公开点赞：${candidate.metrics?.likes ?? '未知'}\n公开收藏：${candidate.metrics?.saves ?? '未知'}\n公开评论：${candidate.metrics?.comments ?? '未知'}\n正文：${candidate.body || '未识别'}\n话题：${JSON.stringify(candidate.tags || [])}\n\n返回对象：{\n  "textScore": 0到100整数,\n  "summary": "文本侧一句话判断",\n  "tags": ["最多4个标签"],\n  "structure": ["最多5个文本结构步骤"],\n  "hooks": ["最多3个文本钩子策略"],\n  "valuePoints": ["最多3个价值卖点"],\n  "concerns": ["最多3个用户顾虑"],\n  "risks": ["事实或原创风险"],\n  "textStrengths": ["文本为什么有效"],\n  "textWeaknesses": ["文本侧不足"],\n  "recommended": true或false\n}`;
}

function candidateVisionPrompt(candidate, imageCount) {
  return `分析这组${candidate.platform || '图文平台'}公开图文图片，共${imageCount}张。你只负责报告图片中实际可见的信息，不得根据标题补写图片里没有的内容。\n候选标题：${candidate.title}\n目标关键词：${candidate.keyword || ''}\n\n返回严格JSON对象：{\n "visualScore": 0到100整数,\n "coverHook": "封面如何吸引点击",\n "visualSummary": "整组图片一句话概括",\n "pages": [{"index":1,"visibleText":"图片内可见文字/OCR","scene":"人物商品场景","layout":"构图与信息层级","colors":"配色","role":"这张图在叙事中的作用"}],\n "sequence": ["图片组叙事节奏"],\n "visualHooks": ["最多4个视觉钩子"],\n "generationHints": ["供后续生图使用的视觉描述，不得要求复制原图"],\n "risks": ["品牌、肖像、版权、事实或敏感风险"],\n "lowConfidencePages": [1]\n}`;
}

function candidateSynthesisPrompt(candidate, textAnalysis, visionAnalysis) {
  return `对一条候选图文做最终复审。文本初析和视觉报告来自两个独立模型。交叉检查，不得把视觉模型的不确定描述当成事实，也不得要求复制原文或原图。\n\n原始标题：${candidate.title}\n原始正文：${candidate.body || ''}\n公开数据：${JSON.stringify(candidate.metrics || {})}\n文本初析：${JSON.stringify(textAnalysis)}\n视觉报告：${JSON.stringify(visionAnalysis)}\n\n返回严格JSON对象：{\n "score": 0到100整数,\n "summary": "综合判断",\n "tags": ["最多4个标签"],\n "structure": ["最多6个可复用内容结构"],\n "hooks": ["文本与视觉综合钩子"],\n "valuePoints": ["价值卖点"],\n "concerns": ["用户顾虑"],\n "risks": ["事实、品牌、版权与原创风险"],\n "recommended": true或false,\n "productionBlueprint": {\n   "topic":"原创选题方向",\n   "audience":"目标受众",\n   "tone":"表达语气",\n   "textPlan":["正文组织步骤"],\n   "imagePlan":[{"index":1,"purpose":"本页作用","copy":"本页建议文案","visualPrompt":"后续生图描述","avoid":["不得复制的来源元素"]}],\n   "mustVerify":["生产前必须人工核实的事实"]\n }\n}`;
}

function generationPrompt(candidate, count, context = '', enterprise = {}, imageRules = {}) {
  const platform = candidate.platform || '图文平台';
  return `你正在执行企业内部图文“一做”的策划阶段，目标发布平台是${platform}。爆款只可学习内容与视觉机制，企业素材才是内容主角。\n\n【爆款参考】\n来源平台：${platform}\n来源标题：${candidate.title}\n来源正文：${candidate.body || '未识别正文'}\n文本结构：${JSON.stringify(candidate.structure || [])}\n视觉拆解：${JSON.stringify(candidate.visionAnalysis || {})}\n综合蓝图：${JSON.stringify(candidate.analysis?.productionBlueprint || {})}\n\n【必须融合的企业素材库】\n品牌：${enterprise.brandName || ''}\n产品/服务：${enterprise.productName || ''}\n定位：${enterprise.positioning || ''}\n目标人群：${enterprise.audience || ''}\n账号语气：${enterprise.brandVoice || ''}\n真实事实：${JSON.stringify(enterprise.productFacts || [])}\n卖点：${JSON.stringify(enterprise.sellingPoints || [])}\n证据/资质：${JSON.stringify(enterprise.proofPoints || [])}\n禁止宣传/红线：${JSON.stringify(enterprise.forbiddenClaims || [])}\n企业视觉规则：${JSON.stringify(enterprise.visualRules || [])}\n企业图片素材（仅可按可见内容和用途使用，编号会被后端核验）：${JSON.stringify(enterprise.imageAssets || [])}\n\n【图片硬约束】\n${JSON.stringify(imageRules)}\n附加要求：${context || '无'}\n\n必须遵循：\n1. 一组图片必须有明确视觉主线和逐页分工。第一页承担停留钩子，后续页承担证据、过程、对比、清单、产品或行动中的不同职责。\n2. 每页 imagePrompt 必须完整写出是否带字、文字内容与语言、主体、场景、镜头、构图、连续性、风格和禁用项；人工会在工作台查看和修改，后端不会补充隐藏要求。\n3. imagePrompt 必须是可直接发送给生图模型的最终草稿，不得依赖后端补充上下文。\n4. 每套必须使企业成为主角：正文至少使用一条给出的真实事实或卖点。存在企业图片素材时必须使用合法素材编号，并在 assetUsage 说明出现页、用途和不可改动项；没有图片素材时不得虚构编号。不得把企业资料仅作为结尾广告。\n5. 只能使用企业图片素材可见内容和 immutableNotes 允许的元素；不得臆造包装、Logo、认证或检测结果。\n6. 不得复制来源原句、人物、案例、画面或版式。\n7. 标题和正文是给消费者看的最终发布内容，严禁出现“企业素材库、企业资料库、占位信息、未提供资料、系统、模型、提示词、AI工作流”等内部生产术语；资料不足时不要解释或编造。\n8. 每页 copy 都必须提供不超过28字的可编辑页面文案；最终是否把文字绘制到图片中，必须完整写入工作台可见的 imagePrompt。\n\n创作 ${count} 套差异化原创${platform}图文。返回严格对象：{ "variants": [{ "title":"适合目标平台的精炼标题", "body":"完整正文", "tags":["不带#"], "format":"内容形式", "audience":"目标受众", "enterpriseGrounding":{"productAngle":"本套如何服务企业产品/服务","factsUsed":["必须逐字来自企业真实事实或卖点"],"sellingPointsUsed":["必须逐字来自企业卖点"],"proofPointsUsed":["必须逐字来自企业证据，可为空"],"assetIds":["必须是给定企业图片素材编号；没有可用图片时可为空"],"assetUsage":["素材编号：第几页如何使用、不可改动什么；没有可用图片时可为空"]}, "visualStrategy":{"concept":"整组视觉概念","coverHook":"首图停留机制","continuity":"全组统一规则","palette":["主色"],"avoidGeneric":["避免泛化的要求"]}, "imagePages":[{"role":"cover|evidence|process|comparison|list|product|action","purpose":"本页不可替代的作用","copy":"不超过28字的可编辑页面文案，任何模式都不能为空","imagePrompt":"可直接发送给生图模型的完整提示词"}] }] }。每套必须恰好 ${imageRules.imageCount || 4} 页，variants 必须恰好 ${count} 条。`;
}

function imageQualityPrompt(variant, page, rules = {}, enterprise = {}) {
  return `你是企业图文工作流的视觉质检 Agent。只评价所见图片，不得假设图片里不存在的内容。\n目标平台：${variant.platform || '图文平台'}\n标题：${variant.title}\n正文目标：${variant.body.slice(0, 800)}\n整组视觉策略：${JSON.stringify(variant.visualStrategy || {})}\n当前页：${JSON.stringify({ index:page.index, role:page.role, purpose:page.purpose, copy:page.copy, prompt:page.imagePrompt })}\n图片规则：${JSON.stringify(rules)}\n企业视觉规则：${JSON.stringify(enterprise.visualRules || [])}\n\n按目标平台图文成品标准检查：首屏停留力、信息表达、与标题正文相关性、主体清晰度、构图与留白、系列一致性、真实感/AI瑕疵、人物手部与食物形态、品牌/文字/二维码风险。图片规则中的 size 是供应商实际输出画布，aspectRatio 与它严格一致；图片像素符合 size 时不得以其他平台经验比例为由扣分。严格按照当前页工作台可见的 copy 与 imagePrompt 判断文字、构图和内容是否符合要求；不得引用已删除的隐藏文字模式。\n返回严格 JSON：{"score":0到100,"passed":true或false,"summary":"一句话结论","strengths":["优点"],"problems":["具体问题"],"retryPrompt":"若不通过，给一条保留原目标但能明确修正问题的完整生图提示词；通过则为空"}。`;
}

function performancePrompt(variant, metrics, baseline = {}, snapshots = [], options = {}) {
  return `这是企业内部图文“二次分析”。分析已发布笔记的真实后台数据，判断结果来自标题、首图、正文结构、图片、账号基线或发布时间中的哪些可观察因素；不能把相关性说成因果，也不能编造平台未提供的流量来源。\n\n标题：${variant.title}\n正文摘要：${variant.body.slice(0, 500)}\n发布时间：${variant.publishedAt || '未知'}\n本次采样来源：${metrics.source || '人工回填'}\n曝光：${metrics.exposure}\n观看：${metrics.views ?? metrics.exposure}\n封面点击率：${metrics.coverClickRate ?? '平台未提供'}\n点赞：${metrics.likes}\n收藏：${metrics.saves}\n评论：${metrics.comments}\n涨粉：${metrics.followers ?? '平台未提供'}\n分享：${metrics.shares ?? '平台未提供'}\n人均观看时长：${metrics.averageViewSeconds ?? '平台未提供'}秒\n\n同账号基线：${JSON.stringify(baseline)}\n历史采样序列（只可据此描述趋势）：${JSON.stringify(snapshots)}\n本轮是否已到最终观察节点：${options.final ? '是' : '否，只能给阶段性建议，不得要求立即放大'}\n\n返回对象：{ "decision": "scale|test|stop", "reason": "明确说明判断依据和不确定性", "winningElements": ["最多5个已验证或待继续验证的胜出元素"], "nextDirections": ["下一轮最多5个方向"], "keep": ["二做必须保留的元素"], "change": ["二做只应修改的变量"], "evidence": ["对应的数据证据"], "confidence": 0到100整数 }。`;
}

module.exports = { SYSTEM, candidateTextAnalysisPrompt, candidateVisionPrompt, candidateSynthesisPrompt, generationPrompt, imageQualityPrompt, performancePrompt };
