import { spawn } from 'node:child_process';
import { createServer } from 'node:http';
import { rm } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');const data=resolve(process.env.TEMP||root,`ContentOpsAgentV2-QA-master-control-${process.pid}`);const port=17843;await rm(data,{recursive:true,force:true});
const ai=createServer(async(req,res)=>{let raw='';for await(const c of req)raw+=c;const isVision=req.url.endsWith('/responses');res.writeHead(200,{'content-type':'application/json'});res.end(isVision?JSON.stringify({output:[{content:[{type:'output_text',text:'{"ok":true,"summary":"test"}'}]}],usage:{input_tokens:1,output_tokens:1}}):JSON.stringify({choices:[{message:{content:'{"ok":true,"message":"test"}'}}],usage:{prompt_tokens:1,completion_tokens:1}}));});await new Promise(d=>ai.listen(19993,'127.0.0.1',d));
const child=spawn(process.execPath,[resolve(root,'server.cjs')],{cwd:root,env:{...process.env,CONTENTOPS_PORT:String(port),CONTENTOPS_DATA_DIR:data},windowsHide:true,stdio:['ignore','pipe','pipe']});const post=(route,body={})=>fetch(`http://127.0.0.1:${port}${route}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}).then(r=>r.json());const get=()=>fetch(`http://127.0.0.1:${port}/api/state`).then(r=>r.json());
try{for(let i=0;i<80;i++){try{if((await fetch(`http://127.0.0.1:${port}/health`)).ok)break;}catch{}await new Promise(d=>setTimeout(d,100));}let result=await post('/api/workflow/run');if(result.code!=='MASTER_STOPPED')throw new Error('默认状态未禁止工作流');result=await post('/api/master/start');if(result.ok)throw new Error('未配置Key时不应开始总控');await post('/api/settings/save',{workflowAutoEnabled:false,xhsEnabled:true,xhsKeywords:['测试'],manualRawLimit:30,automaticRawLimit:50,manualFinalLimit:10,automaticFinalLimit:10,generationCount:3,scaleGenerationCount:2,dailyBudget:10,aiBaseUrl:'http://127.0.0.1:19993/v1',aiModel:'test',aiInputPricePerMillion:1,aiOutputPricePerMillion:1,visionDailyBudget:10,visionBaseUrl:'http://127.0.0.1:19993/v1',visionModel:'test',visionInputPricePerMillion:1,visionOutputPricePerMillion:1,visionMaxImages:2});await post('/api/ai/credential/save',{apiKey:'a'});await post('/api/vision/credential/save',{apiKey:'v'});await post('/api/ai/test');await post('/api/vision/test');result=await post('/api/master/start');if(!result.ok)throw new Error(result.message);let state=await get();if(!state.settings.masterEnabled)throw new Error('总控未持久化开始');await post('/api/master/stop');state=await get();if(state.settings.masterEnabled||state.settings.workflowAutoEnabled)throw new Error('总控停止未关闭调度');result=await post('/api/settings/save',{workflowAutoEnabled:true,xhsEnabled:true,xhsKeywords:['测试'],manualRawLimit:30,automaticRawLimit:50,manualFinalLimit:10,automaticFinalLimit:10,generationCount:3,scaleGenerationCount:2,dailyBudget:10,visionDailyBudget:10,visionMaxImages:2});state=await get();if(!result.ok||result.automationEnabled||state.settings.workflowAutoEnabled||state.settings.collectionEnabled)throw new Error('总控停止后保存设置不应暗中重新开启调度');result=await post('/api/collection/run',{platform:'小红书',manual:true});if(result.code!=='MASTER_STOPPED')throw new Error('停止后仍可抓取');result=await post('/api/master/start');if(!result.ok)throw new Error(`停止后无法重新启动总控：${result.message}`);state=await get();const analyst=state.agents.find(item=>item.id==='analyst');const creator=state.agents.find(item=>item.id==='creator');if(analyst?.status!=='healthy'||analyst?.detail!=='评分队列为空'||creator?.status!=='idle'||creator?.detail!=='等待人工选款')throw new Error(`总控重启后子Agent状态残留：${JSON.stringify({analyst,creator})}`);console.log(JSON.stringify({status:'PASS',defaultStopped:true,keyVerificationRequired:true,startWorks:true,stopBlocksCollection:true,persistentStopped:true,settingsCannotReenableAutomation:true,restartResetsChildAgentStatus:true},null,2));}finally{child.kill();ai.close();await new Promise(d=>setTimeout(d,300));await rm(data,{recursive:true,force:true});}
